### ISSUE TITLE
onClick in FabConfig

### ISSUE THREAD

**Issue by JesterXL** [aforemny/material-components-elm#36]
I'm getting a compiler error with Fab button's onClick:

```elm
The `fabConfig` record does not have a `onClick` field:

390|     fab { fabConfig | trailingIcon = True, onClick = Just action }
```

I'm wondering I'm importing something wrong, or using the Msg type wrong. The docs imply `onClick` is part of `FabConfig`:

```elm
import Material.Fab exposing (fab, fabConfig)
    type Msg
        = FabClicked
    main =
        fab { fabConfig | onClick = Just FabClicked }
            "favorite"
``` 

I tried to monkey patch `onClick` into `FabConfig` in the `Fab.elm` file but failed. Any hints?

**Comment by JesterXL** [comment]
Ok, I think I figured it out. I had to use the `additionalAttributes` as a List, and ditch the Maybe.

```elm
createNewCollectionButton action =
    extendedFab { extendedFabConfig | trailingIcon = True, additionalAttributes = [onClick action] }
                "Create"
```

**Comment by JesterXL** [comment]
Maybe the docs example should be the following?

```elm
main =
        fab { fabConfig | additionalAttributes = [onClick FabClicked] }
            "favorite"
```

**Comment by aforemny** [comment]
Hi @JesterXL, it is actually an oversight that `fabConfig` and `extendedFabConfig` do not expose a configuration field `onClick : Maybe msg`. I will fix that shortly! Thank you for reporting this issue.

Users should not have to go through `additionalAttributes` for basic functionality of components.

**Comment by aforemny** [comment]
Hi @JesterXL, I just pushed a fix to master. Please use your original code to add the click handler:

```
fab { fabConfig | onClick = Just FabClicked } "favorite"
```

**Comment by JesterXL** [comment]
Booya, works! Thanks a ton.
