### ISSUE TITLE
Hot Module Reload not registering dynamically created Tab onClick

### ISSUE THREAD

**Issue by JesterXL** [aforemny/material-components-elm#37]
This is a fun one. HMR isn't registering my onClick's if they're created dynamically. I'm not sure it's HMR, just would rather blame it vs me. Still debugging.

**Comment by aforemny** [comment]
Hi @jesterxl, would you happen to have a small, reproducible example for me that I could test? I would be happy to take a look at it as well.

**Comment by aforemny** [comment]
Hi @JesterXL, any update on this one?

**Comment by aforemny** [comment]
Closing this issue as stale. @JesterXL feel free to reopen!

**Comment by JesterXL** [comment]
Sorry, no. It's not the components, it's `--hot`, whether elm-live or any hot module reloading. It's mutating variables which... well, I think we should not fix out of principle that mutating things is not ok, lol! Apologies for the latency on this.

**Comment by aforemny** [comment]
Hi @JesterXL, thanks for getting back to me. If you could be so kind to provide instructions on how to reproduce this I would be happy to take a look. I am not intending to spend a lot of time fixing this, but I would be curious to find out what's going on.

I have not worked with hot reloading and I have not worked with elm-live or something similar like that before. So if instructions are just use elm-live and have a single button, and add another button and see the first button not working after hot-reloading, then that would be valuable information for me as well.

If you do not have the time to get back to me, that's fine. But if you do I would appreciate it. Thanks!
